CREATE TABLE IF NOT EXISTS TABLE_PREFIX_PLAYER
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid CHAR(36) UNIQUE NOT NULL,
  name VARCHAR(16) NOT NULL,
  CONSTRAINT unique_uuid_cs UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS TABLE_PREFIX_BLOCKBALL_STATS
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  shy_player_id REFERENCES TABLE_PREFIX_PLAYER(id),
  wins INTEGER,
  games INTEGER,
  goals INTEGER,
  CONSTRAINT foreignkey_player_id_cs FOREIGN KEY (shy_player_id) REFERENCES TABLE_PREFIX_PLAYER(id),
  CONSTRAINT wins_small_games_cs CHECK (wins <= games)
)