rootProject.name = "blockball-root"
include("blockball-api")
include("blockball-bukkit-api")
include("blockball-bukkit-plugin")
include("blockball-bukkit-plugin:blockball-bukkit-nms-108R3")
include("blockball-bukkit-plugin:blockball-bukkit-nms-109R2")
include("blockball-bukkit-plugin:blockball-bukkit-nms-110R1")
include("blockball-bukkit-plugin:blockball-bukkit-nms-111R1")
include("blockball-bukkit-plugin:blockball-bukkit-nms-112R1")
include("blockball-bukkit-plugin:blockball-bukkit-nms-113R2")
include("blockball-bukkit-plugin:blockball-bukkit-nms-114R1")
include("blockball-bukkit-plugin:blockball-bukkit-nms-115R1")
include("blockball-core")
include("blockball-sponge-api")
include("blockball-sponge-plugin")
include("blockball-sponge-plugin:blockball-sponge-nms-112R1")
include("blockball-tools")