rootProject.name = "blockball-root"
include("blockball-api")
include("blockball-bukkit-api")
include("blockball-bukkit-plugin")
include("blockball-bukkit-plugin:bukkit-nms-117R1")
include("blockball-bukkit-plugin:bukkit-nms-118R1")
include("blockball-bukkit-plugin:bukkit-nms-118R2")
include("blockball-bukkit-plugin:bukkit-nms-119R1")
include("blockball-bukkit-plugin:bukkit-nms-119R2")
include("blockball-bukkit-plugin:bukkit-nms-119R3")
include("blockball-bukkit-plugin:bukkit-nms-120R1")
include("blockball-core")
include("blockball-tools")
