name: BlockBall
version: 7.8.0
author: Shynixn
website: https://www.spigotmc.org/members/shynixn.63455/
main: com.github.shynixn.blockball.BlockBallPlugin
softdepend: [ BossBarAPI, PlaceholderAPI, Vault ]
api-version: 1.13
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.20.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.20.0
  - com.google.inject:guice:7.0.0
  - com.google.code.gson:gson:2.10.1
  - com.zaxxer:HikariCP:5.1.0
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.25
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3
  - aopalliance:aopalliance:1.0
